In [1]:
import os
import numpy as np
import pandas as pd

path = os.getcwd()

In [2]:
#Load in dictionary of arteries

vessel_df = pd.read_pickle ('./SysArteries.pkl')
display(vessel_df)

,Name,lam,Radius Values,End Condition
0,aorta_0,6.003781,"[12.5, 11.4]","[1, 2]"
1,aorta_1,1.59,"[11.4, 11.1]","[3, 4]"
2,right_subclavian_artery_0,5.0,"[7, 7]","[5, 6]"
3,aorta_2,0.758033,"[11.1, 10.9]","[7, 8]"
4,left_common_cartoid_artery_0,104.527284,"[2.0930494756709175, 1.7054911275342857]",ST
...,...,...,...,...
338,arteries_rleg28_0,139.086316,"[0.2755204774363098, 0.17351807117222803]",ST
339,arteries_lleg21_3,92.75852,"[0.27596090514371124, 0.27459421879102147]",ST
340,arteries_lleg19_0,221.768222,"[0.1801839607193014, 0.17067838755459327]",ST
341,arteries_lleg28_1,66.908224,"[0.38420728718640085, 0.3226221270644884]",ST
342,arteries_lleg23_0,141.467505,"[0.2761283849630335, 0.2399647470053623]",ST

In [7]:
filtered_df = vessel_df[vessel_df['End Condition'] == 'ST']
display(filtered_df)

,Name,lam,Radius Values,End Condition
4,left_common_cartoid_artery_0,104.527284,"[2.0930494756709175, 1.7054911275342857]",ST
6,art_carotid_0,58.0,"[2.9, 2.8]",ST
10,right_carotid_artery_0,182.863106,"[1.0372402320543708, 1.4077383015410248]",ST
14,left_vertebral_arteries_0,165.608679,"[1.1904511587681472, 1.5347570064681884]",ST
18,superior_mesenteric_artery_0,122.922092,"[1.7587298532332765, 1.668764021716361]",ST
...,...,...,...,...
338,arteries_rleg28_0,139.086316,"[0.2755204774363098, 0.17351807117222803]",ST
339,arteries_lleg21_3,92.75852,"[0.27596090514371124, 0.27459421879102147]",ST
340,arteries_lleg19_0,221.768222,"[0.1801839607193014, 0.17067838755459327]",ST
341,arteries_lleg28_1,66.908224,"[0.38420728718640085, 0.3226221270644884]",ST
342,arteries_lleg23_0,141.467505,"[0.2761283849630335, 0.2399647470053623]",ST

In [10]:
#For each location in mirroring chart (Left side) determine lrr as a function Rd
intial_guess = np.empty([0,2])

for vessel in filtered_df.index.values.tolist():
    item = [vessel, 1] 
    

    
    intial_guess = np.append(intial_guess,[item],axis = 0)
print(intial_guess)

[[  4.   1.]
 [  6.   1.]
 [ 10.   1.]
 [ 14.   1.]
 [ 18.   1.]
 [ 24.   1.]
 [ 26.   1.]
 [ 35.   1.]
 [ 39.   1.]
 [ 40.   1.]
 [ 42.   1.]
 [ 46.   1.]
 [ 47.   1.]
 [ 49.   1.]
 [ 50.   1.]
 [ 51.   1.]
 [ 52.   1.]
 [ 54.   1.]
 [ 56.   1.]
 [ 57.   1.]
 [ 58.   1.]
 [ 60.   1.]
 [ 61.   1.]
 [ 68.   1.]
 [ 69.   1.]
 [ 70.   1.]
 [ 71.   1.]
 [ 74.   1.]
 [ 75.   1.]
 [ 76.   1.]
 [ 78.   1.]
 [ 79.   1.]
 [ 80.   1.]
 [ 82.   1.]
 [ 86.   1.]
 [ 88.   1.]
 [ 89.   1.]
 [ 91.   1.]
 [ 92.   1.]
 [ 94.   1.]
 [ 96.   1.]
 [ 98.   1.]
 [104.   1.]
 [105.   1.]
 [106.   1.]
 [108.   1.]
 [114.   1.]
 [116.   1.]
 [118.   1.]
 [121.   1.]
 [122.   1.]
 [124.   1.]
 [125.   1.]
 [126.   1.]
 [127.   1.]
 [130.   1.]
 [131.   1.]
 [134.   1.]
 [136.   1.]
 [138.   1.]
 [139.   1.]
 [140.   1.]
 [142.   1.]
 [143.   1.]
 [144.   1.]
 [148.   1.]
 [152.   1.]
 [158.   1.]
 [159.   1.]
 [160.   1.]
 [161.   1.]
 [162.   1.]
 [163.   1.]
 [164.   1.]
 [165.   1.]
 [166.   1.]
 [168.   1.]
 [169.   1.]
 [171.   1.]
 [172.   1.]
 [174.   1.]
 [175.   1.]
 [180.   1.]
 [182.   1.]
 [183.   1.]
 [184.   1.]
 [185.   1.]
 [186.   1.]
 [187.   1.]
 [188.   1.]
 [189.   1.]
 [190.   1.]
 [193.   1.]
 [195.   1.]
 [196.   1.]
 [198.   1.]
 [200.   1.]
 [202.   1.]
 [203.   1.]
 [204.   1.]
 [205.   1.]
 [206.   1.]
 [208.   1.]
 [209.   1.]
 [210.   1.]
 [220.   1.]
 [226.   1.]
 [228.   1.]
 [231.   1.]
 [232.   1.]
 [233.   1.]
 [234.   1.]
 [236.   1.]
 [239.   1.]
 [240.   1.]
 [242.   1.]
 [244.   1.]
 [248.   1.]
 [250.   1.]
 [252.   1.]
 [254.   1.]
 [256.   1.]
 [258.   1.]
 [260.   1.]
 [262.   1.]
 [264.   1.]
 [266.   1.]
 [267.   1.]
 [268.   1.]
 [270.   1.]
 [272.   1.]
 [274.   1.]
 [276.   1.]
 [280.   1.]
 [282.   1.]
 [286.   1.]
 [289.   1.]
 [290.   1.]
 [291.   1.]
 [292.   1.]
 [293.   1.]
 [294.   1.]
 [297.   1.]
 [298.   1.]
 [299.   1.]
 [300.   1.]
 [301.   1.]
 [302.   1.]
 [303.   1.]
 [305.   1.]
 [307.   1.]
 [309.   1.]
 [311.   1.]
 [312.   1.]
 [315.   1.]
 [316.   1.]
 [319.   1.]
 [320.   1.]
 [323.   1.]
 [324.   1.]
 [329.   1.]
 [330.   1.]
 [333.   1.]
 [334.   1.]
 [335.   1.]
 [336.   1.]
 [337.   1.]
 [338.   1.]
 [339.   1.]
 [340.   1.]
 [341.   1.]
 [342.   1.]]

In [11]:
#Write as a txt file
np.savetxt('lrr_factor.txt',intial_guess)